name: "Healthy - development"

# only execute workflow on the master branch
on:
  push:
    branches: master

jobs:
  buildAndPublish:
    name: Build and publish dev docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # build healthy-api image and push it to docker hub
      - name: Build and push healthy-api image
        uses: docker/build-push-action@v4
        with:
          context: healthy-api
          tags: dev
      # build healthy-ui image and push it to docker hub
      - name: Build and push healthy-ui image
        uses: docker/build-push-action@v4
        with:
          context: healthy-ui
          tags: dev
