name: "Healthy - pull requests"

# only execute workflow on pull requests
on:
  pull_request:
    branches:
      - master

jobs:
  buildAndTest:
    name: Build and publish dev docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test tag refs
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      # build healthy-api image and push it to docker hub
      - name: Build and push healthy-api image
        uses: docker/build-push-action@v4
        with:
          context: healthy-api/
          push: false
      # build healthy-ui image and push it to docker hub
      - name: Build and push healthy-ui image
        uses: docker/build-push-action@v4
        with:
          context: healthy-ui/
          push: false
