name: "Healthy - releases"

# only execute workflow on the master branch
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  healthy-api:
    name: Build and publish healthy-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # build healthy-api image and push it to docker hub
      - name: Build and push healthy-api image
        uses: docker/build-push-action@v4
        with:
          context: healthy-api
          tags: ${{ env.RELEASE_VERSION }}

  healthy-ui:
    name: Build and publish healthy-ui
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # build healthy-ui image and push it to docker hub
      - name: Build and push healthy-ui image
        uses: docker/build-push-action@v4
        with:
          context: healthy-ui
          tags: ${{ env.RELEASE_VERSION }}

  release_healthy:
    name: Release healthy-api and healthy-ui
    runs-on: ubuntu-latest
    needs: [healthy-api, healthy-ui]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # release a new version on github
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_FILE: none
          RELEASE_NAME_PREFIX: "Release "
